apiVersion: v2
kind: Service
metadata:
  name: nginx-web
  labels:
    app: nginx-web
spec:
  ports:
    # the port that this service should serve on
  - port: 7777
    targetPort: 80
  selector:
    app: nginx-web
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: nginx-web
  name: nginx-web
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-web
      name: nginx-web
    spec:
      containers:
      containers:
      - imagePullPolicy: IfNotPresent
        name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
          hostPort: 50000
          name: "http"
