root = "C:\\containerd\\data\\root"
state = "C:\\containerd\\data\\state"

[grpc]
  address = "\\\\.\\pipe\\containerd-containerd"
  max_recv_message_size = 16777216
  max_send_message_size = 16777216

[debug]
  address = ""
  level = "debug"

[metrics]
  address = ""
  grpc_histogram = false

[cgroup]
  path = ""

[plugins]
  [plugins.cri]
    stream_server_address = "127.0.0.1"
    stream_server_port = "0"
    enable_selinux = false
    sandbox_image = "k8s.gcr.io/pause:3.1"
    stats_collect_period = 10
    systemd_cgroup = false
    enable_tls_streaming = false
    max_container_log_line_size = 16384
    [plugins.cri.containerd]
      snapshotter = "windows-lcow"
      no_pivot = false
      [plugins.cri.containerd.default_runtime]
        runtime_type = "io.containerd.runhcs.v1"
      [plugins.cri.conatinerd.runtimes]
        [plugins.cri.containerd.runtimes.wcow]
          runtime_type = "io.containerd.runhcs.v1"
          [plugins.cri.containerd.runtimes.wcow.options]
            SandboxImage = "mcr.microsoft.com/windows/nanoserver:1809"
            SandboxPlatform = "windows/amd64"
        [plugins.cri.containerd.runtimes.wcow-debug]
          runtime_type = "io.containerd.runhcs.v1"
          [plugins.cri.containerd.runtimes.wcow-debug.options]
            SandboxImage = "mcr.microsoft.com/windows/nanoserver:1809"
            SandboxPlatform = "windows/amd64"
            Debug = true
        [plugins.cri.containerd.runtimes.wcow-isolated]
          runtime_type = "io.containerd.runhcs.v1"
          [plugins.cri.containerd.runtimes.wcow-isolated.options]
            SandboxImage = "mcr.microsoft.com/windows/nanoserver:1809"
            SandboxPlatform = "windows/amd64"
            SandboxIsolation = 1
        [plugins.cri.containerd.runtimes.wcow-isolated-debug]
          runtime_type = "io.containerd.runhcs.v1"
          [plugins.cri.containerd.runtimes.wcow-isolated-debug.options]
            SandboxImage = "mcr.microsoft.com/windows/nanoserver:1809"
            SandboxPlatform = "windows/amd64"
            SandboxIsolation = 1
            Debug = true
        [plugins.cri.containerd.runtimes.lcow]
          runtime_type = "io.containerd.runhcs.v1"
        [plugins.cri.containerd.runtimes.lcow-debug]
          runtime_type = "io.containerd.runhcs.v1"
          [plugins.cri.containerd.runtimes.lcow-debug.options]
            Debug = true
    [plugins.cri.cni]
      bin_dir = "C:\\k\\cni"
      conf_dir = "C:\\k\\cni\\config"
    [plugins.cri.registry]
      [plugins.cri.registry.mirrors]
        [plugins.cri.registry.mirrors."docker.io"]
          endpoint = ["https://registry-1.docker.io"]
  [plugins.diff-service]
    default = ["windows", "windows-lcow"]
  [plugins.scheduler]
    pause_threshold = 0.02
    deletion_threshold = 0
    mutation_threshold = 100
    schedule_delay = "0s"
    startup_delay = "100ms"
